
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: littlelemon  
      MYSQL_DATABASE: littlelemon
      MYSQL_USER: littlelemon
      MYSQL_PASSWORD: littlelemon
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
